version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: ['tipo:dependências']
    commit-message:
      prefix: build
      include: scope
    groups:
      ferramentas:
        patterns: ['eslint*', '@eslint/*', 'typescript*', 'prettier', 'vitest', '@vitest/*', '@playwright/*']
      react:
        patterns: ['react', 'react-dom', '@types/react*', '@tanstack/*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: ['tipo:dependências']
    commit-message:
      prefix: ci
